version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: canardRootPassword
      MYSQL_DATABASE: canardDB
      MYSQL_USER: canardUser
      MYSQL_PASSWORD: canardPassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: openjdk:17
    container_name: twitter_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run

volumes:
  mysql-data:
